POST http://localhost:3000/posts
Content-Type: application/json

{
    "title":"test title 4",
    "content":"test content 4",
    "slug":"test-title-4",
    "status" : "draft",
    "tags" : [1, 2],
    "featureImgUrl" : "https://codehubmm.com/images/logo.png",
    "publishOn" : "2026-04-29T14:30:00.000Z",
    "meta" : {
        "readTime" : "2 min read"
    },
    "authorId" : 1
}